### ISSUE TITLE
请问gitee页面的cookie的键是哪个。

### ISSUE THREAD

**Issue by linzowo** [mizuka-wu/gitee-pages-action#5]
我看了你文档里的示例，没有在我的项目页面的cookie中找到类似格式的cookie值。请问一下具体取哪个key的值呢

**Comment by mizuka-wu** [comment]
cookie当然是登陆gitee之后用调试看 document.cookie

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: linzowo <notifications@github.com>
发送时间: Friday, November 20, 2020 9:15:36 AM
收件人: mizuka-wu/gitee-pages-action <gitee-pages-action@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [mizuka-wu/gitee-pages-action] 请问gitee页面的cookie的键是哪个。 (#5)


我看了你文档里的示例，没有在我的项目页面的cookie中找到类似格式的cookie值。请问一下具体取哪个key的值呢

―

**Comment by linzowo** [comment]
请问csrf不需要传入action吗。添加了cookie后运行action报错403.

**Comment by mizuka-wu** [comment]
403是方法错了 我有空看一下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: linzowo <notifications@github.com>
发送时间: Friday, November 20, 2020 9:40:06 AM
收件人: mizuka-wu/gitee-pages-action <gitee-pages-action@noreply.github.com>
抄送: Edward Mizuka <mizuka.wu@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [mizuka-wu/gitee-pages-action] 请问gitee页面的cookie的键是哪个。 (#5)


请问csrf不需要传入action吗。添加了cookie后运行action报错403.

―

**Comment by linzowo** [comment]
已更新cookie获取指南，具体情况参考readme文件内容。
